= Bespoke.js Emulating ioslides (aka io-2012-slides)

A http://markdalgleish.com/projects/bespoke.js[Bespoke.js] presentation that emulates the example presentation for https://code.google.com/p/io-2012-slides[ioslides].

WARNING: Not all the information in the slides applies to this presentation.
The content was kept (mostly) the same as in the original template for comparison purposes.

== Highlights

Using Bespoke.js has the following advantages over the original ioslides presentation engine:

* 13.9K of minified JavaScript down from > 70K in ioslides
  - 7K without overview mode
* 11.6K of minified CSS (generated from Stylus instead of Sass) down from 52K in ioslides
* 16.4K of semantic HTML generated from only 4.6K (~ 180 lines) of link:src/index.adoc[AsciiDoc]
* Scales to fit any screen resolution
  - Addresses a major shortcoming in ioslides
* A more powerful and efficient overview mode
* Configurable content builds (aka slide fragments)
* Ready to tap into the Bespoke.js https://www.npmjs.com/browse/keyword/bespoke-plugin[plugin ecosystem]

No matter how you look at it, you'll be a 4x presenter!

NOTE: Presenter mode will be available once integration with https://github.com/opendevise/bespoke-onstage[bespoke-onstage] is complete.

== View slides locally

First, ensure you have the following installed:

. https://www.ruby-lang.org[Ruby]
. http://bundler.io[Bundler]

 $ gem install bundler

. https://nodejs.org[Node.js]
. http://gulpjs.com[Gulp]

 $ npm install -g gulp

Then, install dependencies and run the preview server:

 $ bundle && npm install
 $ gulp serve
